### PR TITLE
#108: added all-of fail output

### LINKED ISSUE #108: all-of-failed-output.eo:28-31: To add several tests for...
The puzzle `41-d652169e` from #41 has to be resolved: 

https://github.com/objectionary/eo-hamcrest/blob//src/test/eo/org/eolang/hamcrest/failed-output/all-of-failed-output.eo#L28-L31

The puzzle was created by graur on 14-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by includealex**
Closes #108

### CODE REVIEW

**Comment by includealex** [comment]
@Graur please review.

**Review by Graur — APPROVED** [review]
@includealex Thanks!

**Comment by Graur** [comment]
@rultor merge

**Comment by includealex** [comment]
@rultor hello

**Pull request merged**
