### PR TITLE
fix tests according to pdd rules

### PR DESCRIPTION
**Pull request by Graur**

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 I made some more fixes to pass the release checks. Please, have a look.
Btw, do we need a codecov check here? Seems redundant. They have no support of EO.

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@rultor merge

**Review by yegor256 — APPROVED** [review]
I approve

**Comment by Graur** [comment]
@rultor merge

**Pull request merged**
